# Generated by Django 3.1.7 on 2021-03-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210306_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='voter',
            new_name='votes',
        ),
    ]
